version: '2'
services:
  vault:
    ports:
    - 8200:8200/tcp
    labels:
      io.rancher.container.pull_image: always
    image: vault
    environment:
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl":"168h", "max_lease_ttl": "720h"}'
    stdin_open: true
    tty: true
    cap_add:
    - IPC_LOCK
