vault:
  ports:
  - 8200:8200/tcp
  labels:
    io.rancher.container.pull_image: always
  image: vault
  command: "vault server -config=/vault/config/local.json -log-level=info"
  environment:
    VAULT_LOCAL_CONFIG: '{"listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": "1"}}, "storage": {"dynamodb": {"ha_enabled":"false", "region":"eu-west-2", "table": "mgmt-01-rancher-host-mgmt-table", "disable_clustering": "true"}}, "default_lease_ttl":"168h", "max_lease_ttl": "720h"}'
    VAULT_ADDR: http://127.0.0.1:8200
  stdin_open: true
  tty: true
  cap_add:
  - IPC_LOCK
