.catalog:
  name: "NHS Digital - CIS - AUTH App"
  version: "0.18"
  description: "NHS Digital - CIS - AUTH App"
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "auth_version"
      description: "Which version of the app do you want to deploy?"
      label: "Version"
      required: true
      default: portable
      type: "string"
    - variable: "registry_url"
      description: "Please enter the url of your registry"
      label: "e.g. registry.nhs.uk:5000"
      required: true
      default: 446537062602.dkr.ecr.eu-west-2.amazonaws.com/cishackday
      type: "string"
    - variable: "env_shortcode"
      description: "Please enter the shortcode of your environment"
      label: "Environment Shortcode"
      required: true
      default: lh
      type: "string"
    - variable: "gluster_url"
      description: "Please enter your Gluster URL"
      label: "Gluster Service"
      required: true
      type: "string"
      default: "nfs.cis-externals.rancher.internal"
    - variable: "fqdn"
      description: "Please enter your FQDN"
      label: "Service FQDN"
      required: true
      type: "string"
      default: "demo.cis.spine2.ncrs.nhs.uk"
    - variable: "portal_cookie_domain"
      description: "Please enter your cookie domain"
      label: "Cookie Domain"
      required: true
      type: "string"
      default: ".cis.spine2.ncrs.nhs.uk"
    - variable: "auth_service_subject"
      description: "Please enter your auth_service_subject"
      label: "auth_service_subject"
      required: true
      type: "string"
#      default: "abc123"
    - variable: "auth_crl_file1"
      description: "Please enter your auth_crl_file1"
      label: "auth_crl_file1"
      required: true
      type: "string"
      default: "fa8d522408ae23f60068fc9e71fada376c8ba42f"
    - variable: "auth_crl_file2"
      description: "Please enter your auth_crl_file2"
      label: "auth_crl_file2"
      required: true
      type: "string"
      default: "124a88b782c09809c3dca6c6697b09e52ef0f605"
    - variable: "auth_crl_file3"
      description: "Please enter your auth_crl_file3"
      label: "auth_crl_file3"
      required: true
      type: "string"
      default: "c1e86afb603027f500cb93022e6b9b0be4df1f8e"
    - variable: "directoryServer"
      description: "Please enter your Directory server including port"
      label: "Directory Server"
      required: true
      type: "string"
      default: "dfa.auth-local.rancher.internal:10389"
    - variable: "ldap_auth_username"
      description: "Please enter your LDAP Username for Auth queries"
      label: "LDAP Auth Username"
      required: true
      type: "string"
#      default: "cn=admin"
    - variable: "ldap_auth_password"
      description: "Please enter your LDAP Password for Auth queries"
      label: "LDAP Auth Password"
      required: true
      type: "string"
      default: "Password1"
    - variable: "ldap_role_username"
      description: "Please enter your LDAP Username for Role queries"
      label: "LDAP Role Username"
      required: true
      type: "string"
#      default: "cn=admin"
    - variable: "ldap_role_password"
      description: "Please enter your LDAP Password for Role queries"
      label: "LDAP Role Password"
      required: true
      type: "string"
      default: "Password1"
    - variable: "gatling_uid"
      description: "Gating UID"
      label: "Gatling UID"
      required: true
      type: "int"
      default: "644153602037"
    - variable: "gatling_auth_service"
      description: "Auth Host service"
      label: "Auth Host service"
      required: true
      type: "string"
      default: "atn"
    - variable: "gatling_auth_subdomain"
      description: "Auth Host subdomain"
      label: "Auth Host subdomain"
      required: true
      type: "string"
      default: "rt.iam.spine2"
    - variable: "gatling_domain"
      description: "Gatling domain"
      label: "Gatling domain"
      required: true
      type: "string"
      default: "ncrs.nhs.uk"
    - variable: "gatling_sbapi_service"
      description: "ABAPI service"
      label: "ABAPI service"
      required: true
      type: "string"
      default: "atn"
    - variable: "gatling_sbapi_subdomain"
      description: "SBAPI subdomain"
      label: "SBAPI subdomain"
      required: true
      type: "string"
      default: "rt.iam.spine2"
    - variable: "gatling_urs_service"
      description: "URS service"
      label: "URS service"
      required: true
      type: "string"
      default: "wfe"
    - variable: "gatling_urs_subdomain"
      description: "URS subdomain"
      label: "URS subdomain"
      required: true
      type: "string"
      default: "rt.iam.spine2"
    - variable: "gatling_concurrent_users"
      description: "Number of concurrent Users"
      label: "Number of concurrent Users"
      required: true
      type: "int"
      default: "1"
    - variable: "gatling_ramp_up_period"
      description: "Ramp up period"
      label: "Ramp up period"
      required: true
      type: "int"
      default: "1"
    - variable: "gatling_simulation_duration"
      description: "Simulation duration"
      label: "Simulation duration"
      required: true
      type: "int"
      default: "60"
    - variable: "vip_ext_auth"
      description: "VIP Auth Host"
      label: "VIP Auth Host"
      required: true
      type: "string"
      default: "10.196.94.199"
    - variable: "use_aws_s3"
      description: "Use AWS S3 as backup file source"
      label: "Enter YES to use AWS S3 as OpenDJ backup file source"
      required: false
      type: "string"
      default: "PLEASE"

TLS-Service:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 80
    unhealthy_threshold: 3
    healthy_threshold: 2

AuditService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /authauditlogger/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

AuthenticatorService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /authenticator/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

SessionManager:
  upgrade_strategy:
    start_first: true
  scale: 1

  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /sessionmanager/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

SAMLService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /saml/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

TokenValidationService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /amserver/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

Portal:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /portal/ HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

djm:
  upgrade_strategy:
    start_first: false
  scale: 1
  health_check:
    port: 8389
    interval: 3000
    unhealthy_threshold: 3
    request_line: 'GET / HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000
    initializing_timeout: 600000

dfa:
  upgrade_strategy:
    start_first: false
  scale: 1
  health_check:
    port: 8389
    interval: 3000
    unhealthy_threshold: 3
    request_line: 'GET / HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000
    initializing_timeout: 600000

dex:
  upgrade_strategy:
    start_first: false
  scale: 1
  health_check:
    port: 8389
    interval: 3000
    unhealthy_threshold: 3
    request_line: 'GET / HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000
    initializing_timeout: 600000
