.catalog:
  name: "NHS Digital - CIS - AUTH App"
  version: "0.2"
  description: |
    Enter Description Here
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "app_version"
      description: "Which version of the app do you want to deploy?"
      label: "Version"
      required: true
      default: latest
      type: "string"
    - variable: "registry_url"
      description: "Please enter the url of your registry"
      label: "e.g. registry.nhs.uk:5000"
      required: true
      default: registry.ptl.cis.ncrs.nhs.uk:5000
      type: "string"
    - variable: "env_shortcode"
      description: "Please enter the shortcode of your environment"
      label: "Environment Shortcode"
      required: true
      default: lh
      type: "string"
    - variable: "gluster_url"
      description: "Please enter your Gluster URL"
      label: "GlusterURL"
      required: true
      default: gluster.cisptl.local
      type: "string"
Directory:
  external_ips:
    - 192.168.99.1

RedisSessionStore:
  external_ips:
    - 192.168.99.1
    
LB-ABS:
  upgrade_strategy:
    start_first: true
  scale: 1
  load_balancer_config:
    name: lb-abs config

AuditService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /authauditlogger/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000


AuthenticatorService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /authenticator/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

SessionManager:
  upgrade_strategy:
    start_first: true
  scale: 1

  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /sessionmanager/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000
    
SAMLService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /saml/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

TokenValidationService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /amserver/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000
