Directory:
  external_ips:
    - $DIR_IP

RedisSessionStore:
  external_ips:
    - $DIR_IP
    
LB-ABS:
  upgrade_strategy:
    start_first: true
  scale: 1
  load_balancer_config:
    name: lb-abs config

AuditService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /authauditlogger/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000


AuthenticatorService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /authenticator/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

SessionManager:
  upgrade_strategy:
    start_first: true
  scale: 1

  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /sessionmanager/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000
    
SAMLService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /saml/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

TokenValidationService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /amserver/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000