
TLS-Service:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    service_name: TlsService
    project.service.name: tls-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
  image: ${registry_url}/auth-httpd:latest
  tty: true
  stdin_open: true
  environment:
    rINTERNAL_LB: LB-AuthBusinessService:8080
    rREDIS_INSTANCE: ${redisSessionStore}
    rLDAP_LOCATION_ROLE: ${directoryServer}
    rLDAP_LOCATION_AUTH: ${directoryServer}
    rCRL_LOCATION: 10.196.94.238
    rATN_FQDN: gas.${fqdn}
    rAUTH_SERVERID: 192.168.118.105
    rWFE_FQDN: wfe.${fqdn}
    rPORTAL_FQDN: portal.${fqdn}
    rAUDIT_DB: ${auditDatabaseServer}
    rOUT_HOST: 127.0.0.1
    rCRL_FILE: IAM_crlfile.crl
    rAUTH_SERVICE_SUBJECT: ${auth_service_subject}
    rCRL_FILENAME: ${auth_crl_file1}
    rCRL_FILENAME2: ${auth_crl_file2}
    rLDAP_USERNAME_AUTH: ${ldap_auth_username}
    rLDAP_PASSWORD_AUTH: ${ldap_auth_password}
    rLDAP_USERNAME_ROLE: ${ldap_role_username}
    rLDAP_PASSWORD_ROLE: ${ldap_role_password}

LB-AuthBusinessService:
  expose:
  - 8080
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.loadbalancer.target.AuthenticatorService: /authenticator=8080
    io.rancher.loadbalancer.target.TokenValidationService: /amserver=8080
    io.rancher.loadbalancer.target.SAMLService: /saml=8080
    io.rancher.loadbalancer.target.AuditService: /authauditlogger=8080
    io.rancher.loadbalancer.target.SessionManager: /sessionmanager=8080
    environment_name: ${env_shortcode}
    service_name: LB-AuthBusinessService
    project.service.name: lb-auth-business-service
    project.name: cis-auth
    project.stack: auth
  tty: true
  image: rancher/load-balancer-service
  links:
  - AuthenticatorService:AuthenticatorService
  - AuditService:AuditService
  - SessionManager:SessionManager
  - SAMLService:SAMLService
  - TokenValidationService:TokenValidationService
  stdin_open: true

AuditService:
  labels:
    io.rancher.container.pull_image: always
    project.service.name: audit-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  image: ${registry_url}/auth-audit:${auth_version}
  environment:
    rENV_SHORTCODE: ${env_shortcode}
    JAVA_OPTS: -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -Xms1024m -Xmx6144m

AuthenticatorService:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: Authenticator
    project.service.name: authenticator-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  privileged: true
  environment:
    rCRL_FILENAME: ${auth_crl_file1}
    rCRL_FILENAME2: ${auth_crl_file2}
    rENV_SHORTCODE: ${env_shortcode}
    JAVA_OPTS: -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -Xms1024m -Xmx6144m
  image: ${registry_url}/auth-authenticator:${auth_version}
  tty: true
  stdin_open: true

SessionManager:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: SessionManager
    project.service.name: session-manager
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  privileged: true
  environment:
    JAVA_OPTS: -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -Xms1024m -Xmx6144m
    rENV_SHORTCODE: ${env_shortcode}
    GLUSTER_URL: ${gluster_url}
    GLUSTER_FOLDER: ${env_shortcode}
  image: ${registry_url}/auth-sessionmanager:${auth_version}
  tty: true
  stdin_open: true

SAMLService:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: SAMLService
    project.service.name: saml-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  image: ${registry_url}/auth-saml:${auth_version}
  environment:
    rENV_SHORTCODE: ${env_shortcode}
    JAVA_OPTS: -server -Xms256m -Xmx256m  -XX:NewSize=128m   -XX:MaxNewSize=256m   -XX:PermSize=64m  -XX:MaxPermSize=128m  -XX:+UseConcMarkSweepGC  -XX:+UseParNewGC   -XX:ParallelGCThreads=2 -Djava.security.egd=file:/dev/./urandom
  tty: true
  stdin_open: true

TokenValidationService:
  image: ${registry_url}/auth-tokenvalidation:${auth_version}
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: TokenValidationService
    project.service.name: token-validation-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  environment:
    rENV_SHORTCODE: ${env_shortcode}
    JAVA_OPTS: -server -Xms256m -Xmx512m  -XX:NewSize=128m   -XX:MaxNewSize=256m   -XX:PermSize=64m  -XX:MaxPermSize=128m  -XX:+UseConcMarkSweepGC  -XX:+UseParNewGC   -XX:ParallelGCThreads=2 -Djava.security.egd=file:/dev/./urandom

haproxy-internal:
  ports:
    - 80:443/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: haproxy-internal
    project.service.name: haproxy-internal
    project.name: cis-auth
    project.stack: auth
  environment:
    - vip=0.0.0.0
    - be_atn=authenticatorservice.auth-local.rancher.internal
    - be_sml=samlservice.auth-local.rancher.internal
    - be_tvs=tokenvalidationservice.auth-local.rancher.internal
    - envcode=${env_shortcode}
  image: ${registry_url}/auth-haproxy-int:1
  tty: true
  stdin_open: true
  cap_add:
  - SYS_ADMIN
  security_opt:
  - seccomp:unconfined
AutomatedTesting:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: ranchergroup_main=true
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    service_name: $${service_name}
    environment_name: $ENV_SHORTCODE
    service_name: Automated_Testing
    project.service.name: automated_testing
  volumes:
  - /var/log/iam:/home/iam_user/gatling_outputs
  image: $REGISTRY/automated-testing:latest
  tty: true
  stdin_open: true
  environment:
    rUID: $GATLING_UID
    rGATLING_AUTHHOST_SERVICE: $GATLING_AUTHHOST_SERVICE
    rGATLING_URSHOST_SERVICE: $GATLING_URSHOST_SERVICE
    rGATLING_AUTHHOST_SUBDOMAIN: $GATLING_AUTHHOST_SUBDOMAIN
    rGATLING_URSHOST_SUBDOMAIN: $GATLING_URSHOST_SUBDOMAIN
    rGATLING_CONCURRENT_USERS: $GATLING_CONCURRENT_USERS
    rGATLING_RAMP_UP_PERIOD: $GATLING_RAMP_UP_PERIOD
    rGATLING_SIMULATION_DURATION: $GATLING_SIMULATION_DURATION
    rVIP_EXT_AUTH: $VIP_EXT_AUTH