.catalog:
  name: "NHS Digital - CIS - AUTH App"
  version: "0.10"
  description: |
    Enter Description Here
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "auth_version"
      description: "Which version of the app do you want to deploy?"
      label: "Version"
      required: true
      default: latest
      type: "string"
    - variable: "registry_url"
      description: "Please enter the url of your registry"
      label: "e.g. registry.nhs.uk:5000"
      required: true
      default: registry.ptl.cis.ncrs.nhs.uk:5000
      type: "string"
    - variable: "env_shortcode"
      description: "Please enter the shortcode of your environment"
      label: "Environment Shortcode"
      required: true
      default: lh
      type: "string"
    - variable: "gluster_url"
      description: "Please enter your Gluster URL"
      label: "Gluster Service"
      required: true
      type: "string"
      default: "nfs.cis-externals.rancher.internal"
    - variable: "fqdn"
      description: "Please enter your FQDN"
      label: "Service FQDN"
      required: true
      type: "string"
      default: "demo.aws.cishackday.com"
    - variable: "auth_service_subject"
      description: "Please enter your auth_service_subject"
      label: "auth_service_subject"
      required: true
      type: "string"
      default: "abc123"
    - variable: "auth_crl_file1"
      description: "Please enter your auth_crl_file1"
      label: "auth_crl_file1"
      required: true
      type: "string"
      default: "fa8d522408ae23f60068fc9e71fada376c8ba42f"
    - variable: "auth_crl_file2"
      description: "Please enter your auth_crl_file2"
      label: "auth_crl_file2"
      required: true
      type: "string"
      default: "124a88b782c09809c3dca6c6697b09e52ef0f605"

TlsService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 80
    unhealthy_threshold: 3
    healthy_threshold: 2

AuditService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /authauditlogger/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000


AuthenticatorService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /authenticator/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

SessionManager:
  upgrade_strategy:
    start_first: true
  scale: 1

  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /sessionmanager/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

SAMLService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /saml/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000

TokenValidationService:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: 'GET /amserver/?lbchk=1 HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 2000
