TLS-Service:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    service_name: TlsService
    project.service.name: tls-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
  image: ${registry_url}/auth-httpd:${auth_version}
  tty: true
  stdin_open: true
  environment:
    INTERNAL_LB: LB-AuthBusinessService:8080
    REDIS_INSTANCE: RedisSessionStore:6379
    LDAP_ROLE_LOCATION: ${directoryServer}
    LDAP_ROLE_USERNAME: ${ldap_role_username}
    LDAP_ROLE_PASSWORD: ${ldap_role_password}
    LDAP_AUTH_LOCATION: ${directoryServer}
    LDAP_AUTH_USERNAME: ${ldap_auth_username}
    LDAP_AUTH_PASSWORD: ${ldap_auth_password}
    CRL_LOCATION: 10.196.94.238
    ATN_FQDN: gas.${fqdn}
    AUTH_SERVERID: 192.168.118.105
    WFE_FQDN: wfe.${fqdn}
    PORTAL_FQDN: portal.${fqdn}
    PORTAL_COOKIE_DOMAIN: ${portal_cookie_domain}
    AUDIT_DB: ${auditDatabaseServer}
    OUT_HOST:
    OUT_HOST_ENABLED: false
    CRL_FILE: IAM_crlfile.crl
    AUTH_SERVICE_SUBJECT: ${auth_service_subject}
    CRL_FILENAME: ${auth_crl_file1}
    CRL_FILENAME2: ${auth_crl_file2}
    ENV_SHORTCODE: ${env_shortcode}

LB-AuthBusinessService:
  expose:
  - 8080
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.loadbalancer.target.AuthenticatorService: /authenticator=8080
    io.rancher.loadbalancer.target.TokenValidationService: /amserver=8080
    io.rancher.loadbalancer.target.SAMLService: /saml=8080
    io.rancher.loadbalancer.target.AuditService: /authauditlogger=8080
    io.rancher.loadbalancer.target.SessionManager: /sessionmanager=8080
    environment_name: ${env_shortcode}
    service_name: LB-AuthBusinessService
    project.service.name: lb-auth-business-service
    project.name: cis-auth
    project.stack: auth
  tty: true
  image: rancher/load-balancer-service
  links:
  - AuthenticatorService:AuthenticatorService
  - AuditService:AuditService
  - SessionManager:SessionManager
  - SAMLService:SAMLService
  - TokenValidationService:TokenValidationService
  stdin_open: true

AuditService:
  labels:
    io.rancher.container.pull_image: always
    project.service.name: audit-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  image: ${registry_url}/auth-audit:${auth_version}
  environment:
    rENV_SHORTCODE: ${env_shortcode}
    JAVA_OPTS: -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -Xms1024m -Xmx6144m

AuthenticatorService:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: Authenticator
    project.service.name: authenticator-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  privileged: true
  environment:
    rCRL_FILENAME: ${auth_crl_file1}
    rCRL_FILENAME2: ${auth_crl_file2}
    rENV_SHORTCODE: ${env_shortcode}
    JAVA_OPTS: -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -Xms1024m -Xmx6144m
  image: ${registry_url}/auth-authenticator:${auth_version}
  tty: true
  stdin_open: true

SessionManager:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: SessionManager
    project.service.name: session-manager
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  privileged: true
  environment:
    JAVA_OPTS: -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -Xms1024m -Xmx6144m
    rENV_SHORTCODE: ${env_shortcode}
    GLUSTER_URL: ${gluster_url}
    GLUSTER_FOLDER: ${env_shortcode}
  image: ${registry_url}/auth-sessionmanager:${auth_version}
  tty: true
  stdin_open: true
  external_links:
  - cis-externals/Redis:RedisSessionStore

SAMLService:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: SAMLService
    project.service.name: saml-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  image: ${registry_url}/auth-saml:${auth_version}
  environment:
    rENV_SHORTCODE: ${env_shortcode}
    JAVA_OPTS: -server -Xms256m -Xmx256m  -XX:NewSize=128m   -XX:MaxNewSize=256m   -XX:PermSize=64m  -XX:MaxPermSize=128m  -XX:+UseConcMarkSweepGC  -XX:+UseParNewGC   -XX:ParallelGCThreads=2 -Djava.security.egd=file:/dev/./urandom
  tty: true
  stdin_open: true

TokenValidationService:
  image: ${registry_url}/auth-tokenvalidation:${auth_version}
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: TokenValidationService
    project.service.name: token-validation-service
    project.name: cis-auth
    project.stack: auth
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment_name: ${env_shortcode}
    service_name: $${service_name}
    io.rancher.scheduler.affinity:host_label: stackType=auth
  mem_limit: 1572864000
  volumes:
  - /var/log/iam:/var/log/iam
#  - /home/rancher/env_config/${env_shortcode}/authServices.properties:/home/iam_user/careidconfig/authServices.properties
  tty: true
  stdin_open: true
  environment:
    rENV_SHORTCODE: ${env_shortcode}
    JAVA_OPTS: -server -Xms256m -Xmx512m  -XX:NewSize=128m   -XX:MaxNewSize=256m   -XX:PermSize=64m  -XX:MaxPermSize=128m  -XX:+UseConcMarkSweepGC  -XX:+UseParNewGC   -XX:ParallelGCThreads=2 -Djava.security.egd=file:/dev/./urandom

haproxy-internal:
  ports:
    - 80:80
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
    environment_name: ${env_shortcode}
    service_name: haproxy-internal
    project.service.name: haproxy-internal
    project.name: cis-auth
    project.stack: auth
  environment:
    - vip=0.0.0.0
    - be_atn=authenticatorservice.auth-local.rancher.internal
    - be_sml=samlservice.auth-local.rancher.internal
    - be_tvs=tokenvalidationservice.auth-local.rancher.internal
    - be_pot=portal.auth-local.rancher.internal
    - envcode=${env_shortcode}
  image: ${registry_url}/auth-haproxy-int:${auth_version}
  tty: true
  stdin_open: true
  cap_add:
  - SYS_ADMIN
  security_opt:
  - seccomp:unconfined

AutomatedTesting:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    service_name: $${service_name}
    environment_name: ${env_shortcode}
    service_name: Automated_Testing
    project.service.name: automated_testing
  volumes:
  - /var/log/iam:/home/iam_user/gatling_outputs
  image: ${registry_url}/automated-testing:${auth_version}
  tty: true
  stdin_open: true
  environment:
    UID: ${gatling_uid}
    GATLING_AUTH_SERVICE: ${gatling_auth_service}
    GATLING_AUTH_SUBDOMAIN: ${gatling_auth_subdomain}
    GATLING_DOMAIN: ${gatling_domain}
    GATLING_SBAPI_SERVICE: ${gatling_sbapi_service}
    GATLING_SBAPI_SUBDOMAIN: ${gatling_sbapi_subdomain}
    GATLING_URS_SERVICE: ${gatling_urs_service}
    GATLING_URS_SUBDOMAIN: ${gatling_urs_subdomain}
    GATLING_CONCURRENT_USERS: ${gatling_concurrent_users}
    GATLING_RAMP_UP_PERIOD: ${gatling_ramp_up_period}
    GATLING_SIMULATION_DURATION: ${gatling_simulation_duration}
    VIP_EXT_AUTH: ${vip_ext_auth}

Portal:
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    service_name: $${service_name}
    environment_name: ${env_shortcode}
    service_name: Portal
    project.service.name: portal
    project.name: cis-auth
    project.stack: auth
  volumes:
  - /var/log/iam:/var/log/iam
  image: ${registry_url}/auth-portal:${auth_version}
  tty: true
  stdin_open: true
  environment:
    GLUSTER_URL: ${gluster_url}
    GLUSTER_FOLDER: ${env_shortcode}
    GLUSTER_PHOTOS: true
    GLUSTER_REPORTS: true
    JAVA_OPTS: -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=2 -Xms512m -Xmx1500m
  cap_add:
  - SYS_ADMIN
  security_opt:
  - seccomp:unconfined
  external_links:
  - cis-externals/Redis:RedisSessionStore

djm-01:
#  ports:
#   - 4444:4444
#   - 8989:8989
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    service_name: $${service_name}
    environment_name: ${env_shortcode}
    project.service.name: djm
    project.name: cis-auth
    project.stack: auth
  volumes:
  - /var/log/iam:/var/log/iam
  image: ${registry_url}/opendj-djm:${auth_version}
  tty: true
  stdin_open: true
  environment:
    REFERENCESERVER: dir.cis-externals.rancher.internal
    OPENDJ_BIND_USERNAME: cn=Spine2DirMgr
    OPENDJ_BIND_PASSWORD: Password1
    OPENDJ_BACKUP_SOURCE: 
    OPENDJ_BACKUP_FILE: 
    OPENDJ_ENABLE_CHLOG: YES

dfa-01:
#  ports:
#   - 4444:4444
#   - 8989:8989
  labels:
    io.rancher.scheduler.affinity:host_label: stackType=auth
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    service_name: $${service_name}
    environment_name: ${env_shortcode}
    project.service.name: dfa
    project.name: cis-auth
    project.stack: auth
  volumes:
  - /var/log/iam:/var/log/iam
  image: ${registry_url}/opendj-djm:${auth_version}
  tty: true
  stdin_open: true
  environment:
    REFERENCESERVER: djm-01.auth-local.rancher.internal
    OPENDJ_BIND_USERNAME: cn=Spine2DirMgr
    OPENDJ_BIND_PASSWORD: Password1
    OPENDJ_BACKUP_SOURCE:
    OPENDJ_BACKUP_FILE:
    OPENDJ_ROLE: DFA

