IAM-Database:
  net: "host"
  restart: always
  expose:
  - 5432:5432
  ports:
  - 5432:5432/tcp
  labels:
    environment_name: lh
    service_name: Database
    io.rancher.container.dns: true
    project.service.name: iam-database
    project.name: cis
    project.stack: cis-externals
  tty: true
  image: ${registry_url}/cis-dbs:${ext_version}
  stdin_open: true

Dir:
  restart: always
  ports:
  - 389:10389/tcp
  labels:
    environment_name: lh
    service_name: Dir
    io.rancher.container.dns: true
    project.service.name: dir
    project.name: cis
    project.stack: cis-externals
  tty: true
  image: ${registry_url}/dir:${ext_version}
  stdin_open: true
  links:
  - RootCA:rootca

Redis:
  net: "host"
  restart: always
  expose:
  - 6379:6379
  ports:
  - 6379:6379/tcp
  labels:
    environment_name: lh
    service_name: redis
    io.rancher.container.dns: true
    project.service.name: redis
    project.name: cis
    project.stack: cis-externals
  tty: true
  image: library/redis
  stdin_open: true

Nfs:
  restart: always
  expose:
  - 111
  - 2049
  labels:
    environment_name: lh
    service_name: nfs
    project.service.name: nfs
    project.name: cis
    project.stack: cis-externals
  tty: true
  image: ${registry_url}/nfs-server-ubuntu:${ext_version}
  stdin_open: true
  volumes:
  - /home/rancher/gluster:/gv0
  privileged: true
  command: /gv0

RootCA:
  restart: always
  labels:
    environment_name: lh
    service_name: rootca
    io.rancher.container.dns: true
    io.rancher.container.hostname_override: container_name
    project.service.name: root-ca
    project.name: cis
    project.stack: cis-externals
  container_name: rootca
  privileged: true
  tty: true
  image: ${registry_url}/rootca:${ext_version}
  stdin_open: true
  links:
  - RootCA:rootca

SubCA:
  restart: always
  ports:
  - 1443:1443/tcp
  - 1709:1709/tcp
  - 1710:1710/tcp
  - 1829:1829/tcp
  labels:
    environment_name: lh
    service_name: subca
    io.rancher.container.dns: true
    io.rancher.container.hostname_override: container_name
    project.service.name: sub-ca
    project.name: cis
    project.stack: cis-externals
  privileged: true
  tty: true
  image: ${registry_url}/subca:${ext_version}
  stdin_open: true
  links:
  - RootCA:rootca

SubCC:
  restart: always
  ports:
  - 2443:2443/tcp
  - 2709:2709/tcp
  - 2710:2710/tcp
  - 2829:2829/tcp
  labels:
    environment_name: lh
    service_name: subcc
    io.rancher.container.dns: true
    project.service.name: sub-cc
    project.name: cis
    project.stack: cis-externals
  privileged: true
  tty: true
  image: ${registry_url}/subcc:${ext_version}
  stdin_open: true
  links:
  - RootCA:rootca
