name: NHS Digital - Authentication Data Backup
description: |
  Triggers a backup of DJM and archives the resulting files
version: 0.1
category: NHS-Digital
maintainer: NHS-Digital # The maintainer of the catalog entry
license: "N/A" # The license
projectURL: "N/A" # A URL related to the catalog entry
