.catalog:
  name: "NHS Digital - CIS - Auth Externals"
  version: "0.1"
  description: |
    Enter Description Here
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "externals_version"
      description: "Which version of the CIS Externals do you want to deploy?"
      label: "Version"
      required: true
      default: latest
      type: "string"
    - variable: "registry_url"
      description: "Please enter the url of your registry"
      label: "e.g. registry.nhs.uk:5000"
      required: true
      default: registry.ptl.cis.ncrs.nhs.uk:5000
      type: "string"
    - variable: "env_shortcode"
      description: "Please enter the shortcode of your environment"
      label: "Environment Shortcode"
      required: true
      default: lh
      type: "string"
    - variable: "fqdn"
      description: "Please enter your FQDN"
      label: "Service FQDN"
      required: true
      type: "string"
      default: "demo.aws.cishackday.com"
    - variable: "aad_username"
      description: "AuthAuditDB Username"
      label: "Username"
      required: true
      type: "postgres"
      default: "demo.aws.cishackday.com"
    - variable: "aad_password"
      description: "Please enter your Postgres AAD Password"
      label: "Password"
      required: true
      type: "password"
      default: ""
PGHelper:
  scale: 1
  start_on_create: true

AuthAuditDB:
  hostname: rancher-ha-authauditdb-0.ceayqqx7g1ca.eu-west-2.rds.amazonaws.com
  start_on_create: true
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 5432
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 60000

Redis:
  scale: 1
  start_on_create: true
